### PR TITLE
Add Mario Kart Wii Missing Textures & Crash Fix

### PR DESCRIPTION
**Pull request by teconmoon**
This PR is intended to address the following in Mario Kart Wii:

- Consolidate texture changes to one JSON
- Add some missing button textures (with animations) and controller masks
- Fix game crashing with certain Wiimote configurations

Known issue: DIT doesn't support using both **GCPad1** and **Wiimote1** in the same texture. If trying to use both, DIT will always prioritize **Wiimote1** when building the texture. The result is incorrect menu controls when P1 is using a GC controller. The workaround is to use an empty base texture so that if P1 is using a GC controller, the menu buttons are simply missing instead of incorrect. This is a lot less visually distracting.

### CODE REVIEW

**Comment by Venomalia** [comment]
why do you change everything to one JSON?

**Comment by teconmoon** [comment]
> why do you change everything to one JSON?

Just a habit of trying to keep things in as few files as possible, I can split them back out if it makes more sense for the structure of this project.

**Comment by Venomalia** [comment]
i see no advantage in reducing the number of jsons

**Comment by teconmoon** [comment]
> i see no advantage in reducing the number of jsons

I can work on reverting that if you like. Before I do that, do you have any feedback regarding the other changes?

**Comment by Venomalia** [comment]
it would be wise to keep the devices space holder, Especially because currently only GC or Wii can be used

**Comment by teconmoon** [comment]
@Venomalia I am closing this PR for now since I haven't had time to work on this. I will submit a separate smaller PR for the crashing issue that doesn't have all these other changes.

**Pull request closed without merging**
