### PR TITLE
Update DIT for Super Mario Strikers

### PR DESCRIPTION
**Pull request by Kupo91**
Uses HD font

### CODE REVIEW

**Comment by Venomalia** [comment]
They look really very good and fit perfectly with the original!
Good work.

**Comment by Kupo91** [comment]
Just to avoid misunderstandings, most of the font is made by mariostriker and is included in the hd texture pack, available in the dolphin forums. I just extended the font with Ä, Ö, Ü, Á and other european characters which are missing in his pack. I will contribute these textures to the texture pack as soon as I'm done with the other languages besides german.

I just contribute them to DIT aswell, because otherwise the DIT will overwrite the textures from the texture pack and one will end up with a mix from A, B, C etc. in HD and Ä, Ö, Ü in native (because there are other font textures too, which have no buttons included and therefore are not part of DIT).

On the other hand now someone who only uses DIT and not the texture pack will see A, B, C etc. in native and Ä, Ö, Ü in HD. Not sure if this is better... but I think v2 will adress this issue?

Alternatively one have to add the other font textures (without buttons included) to DIT aswell to avoid such a mix from HD and native font. In that case we had to ask mariostriker for permission and I'm not sure if he is still active in the forums.

**Comment by Venomalia** [comment]
I think you can make a region with the "Blank" key and it will be copied over.

**Comment by Venomalia** [comment]
I add it now simply because I assume that he will have nothing against it.

**Pull request merged**
