### PR TITLE
Update Assets and DefaultDevices by mirrored device textures

### PR DESCRIPTION
**Pull request by Kupo91**
# 1st commit #

I noticed that there are no mirrored device textures, so I took a look at the `_Mirror` folder in `#DefaultDevices`. By this I also noticed that the folder `XBOX ONE Series X` is missing in `_Mirror`. So I copied the folder over to `_Mirror` and mirrored the textures. 
Then I checked the json files in `Assets`, if I need to add the new folder in all Mirror Assets, but looks like they don't use this folder. I assume the `XBOX ONE Series X` folder is only used by the `DeviceTextureChanger.bat` ? In this case the DeviceTextureChanger probably needs to be updated to recognize the mirrored textures.

When I checked if the Mirror json files in Assets contain the `XBOX ONE Series X` folder, I had trouble to compare some files because their structure was different.

So what this commit does is rearrange "SDL/0/Switch Pro Controller" in 
- UniversalDIT_Flat.json
- UniversalDIT_Flat_Mirror.json
- UniversalDIT_Text-Default.json

to match the structure of the other json files and make them easier to compare in the future.

Same with "DInput/0/Stadia Controller rev. A" in UniversalDIT_Text-Outlines.json.

# 2nd commit #

This commit adds device textures to the `_Mirror` folder

- _Mirror/DualShock4/Device
- _Mirror/Generic/Device
- _Mirror/Switch_Joy-Con/Device
- _Mirror/Switch_Pro Controller/Device
- _Mirror/XBOX ONE/Device

and updates the json files in `Assets` with a device texture path.

This is also required for a game which I will add DIT for later. The DIT for this game are already tested with these changes and work fine.

### CODE REVIEW

**Comment by Kupo91** [comment]
In 2nd commit I only added lines about the device icon. I don't know why it added a space in the next line. I can't see that space in notepad++ either. So this maybe needs an adjustment. 

You should also take a look at the PS5 controller. It has a space in its device name, but no space in the icon line.

>     " SDL/0/PS5 Controller": {
>      "SDL/0/PS5 Controller": "../#DefaultDevices/DualShock4/Device/Icon.png",

Since I didn't knew if this is intended, I used this name for the the mirror files, too.

**Comment by Venomalia** [comment]
that there is no mirrored devices is wanted.

**Comment by Kupo91** [comment]
Not sure what you mean. I mirrored them, to come from this:

tex1_256x64_bcee0fa85e1ae7d4_9729c2abe2c9453f_9
tex1_256x128_a4e67840aaed311b_b0c87af58ea48fac_9

to this:

G9RD7D_2023-01-07_22-58-11

It won't work without mirrored device textures.

**Comment by Venomalia** [comment]
sorry it took me so long.
could you please first mirror only the textures you need?
I do not want the package to become unnecessarily "larger".

**Comment by Kupo91** [comment]
Sure, I only need the "icon" textures. If size matters, we could also think about deleting the other regular device textures. I can't remember to ever use any other device textures than icon ?

**Comment by Venomalia** [comment]
i would like at least a normal version to remain because we need it when v2 is ready. XD

**Pull request merged**
