### PR TITLE
Update NfS (GC) device textures

### PR DESCRIPTION
**Pull request by Kupo91**

### CODE REVIEW

**Comment by Venomalia** [comment]
Where does the texture of the Gamecube controller come from?

**Comment by Kupo91** [comment]
internet. the glow is photoshopped to make it look like the original.

**Comment by Venomalia** [comment]
i mean the source of the graphic, where did you get it?

**Comment by Kupo91** [comment]
https://www.pikpng.com/transpng/bbTxJi/

**Comment by Venomalia** [comment]
since the license does not match ours, please add a license.txt and link to the source.

**Comment by Venomalia** [comment]
Sorry I was a bit unclear, please write which texture this applies to.

**Pull request merged**
