### PR TITLE
Run automated fixes on Pull Request

### PR DESCRIPTION
**Pull request by Avasam**
Follow-up to #217 . If this is accepted, the next step would be to sign-in on https://pre-commit.ci/ and connect it to this repo. (it's the CI autofixes version of https://pre-commit.com) . 

Added autoformatting and basic linting fixes for YAML, JSON, Markdown and Python files.
As well as autofixes for mixed-line-ending, case-conflict trailing whitespaces and end-of-file newline.

You can run locally using:
- `pip install pre-commit` to install
- `pre-commit run` to run

You can run on all files using `pre-commit run --all-files` (see #221 for an initial run on all files)

Devs who enjoy pre-commit git hooks (I don't, some do), can also now use this as a pre-commit hook on their own accord using `pre-commit install`

Example run:
image

### CODE REVIEW

**Comment by Venomalia** [comment]
I am not a fan of formatting the json files, 
`"Device": [[0.0, 512.0, 2048.0, 1536.0]]`
you should use the same formatting as the 
DolphinDynamicInputTextureCreator tool.

**Comment by Avasam** [comment]
I'll see if I can, otherwise I'll just omit the formatter or use a different one.

Indent fixes are still relevant though.

I prefered showing you the possibility/difference it makes, then reverting if unliked.

**Comment by Avasam** [comment]
@Venomalia The joys of an overly-opinionated formatted ^^ I excluded JSON files from the prettier hook and added a json formatting hook provided by pre-commit directly.

**Comment by Venomalia** [comment]
Looks good!
I guess I can merge it and then create a pre-commit hook.

**Pull request merged**
